/**
 * Branded HTML report renderer.
 *
 * Produces a self-contained HTML document (inline CSS, no external assets
 * except the prospect's logo) where each prospect company is rendered with its
 * own brand accent colour and logo — so a brief about Acme looks like Acme.
 */
import { logoUrl, monogram, readableTextOn, safeAccent } from "../branding/logo.js";
import type { Citation, MeetingBrief, ProspectResearch, Researched } from "../types.js";

const GRANOLA_PURPLE = "#6C5CE7";

export function renderReport(brief: MeetingBrief): string {
  const sections = brief.prospects.map(renderProspect).join("\n");
  const modeBadge = brief.live
    ? `<span class="chip chip-live">LIVE · Parallel</span>`
    : `<span class="chip chip-mock">MOCK DATA</span>`;
  const when = brief.meeting.startsAt ? ` · ${esc(brief.meeting.startsAt)}` : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Pre-meeting brief — ${esc(brief.meeting.title)}</title>
<style>${STYLES}</style>
</head>
<body>
<div class="wrap">
  <header class="top">
    <div class="brand">🥣 <span>Granola</span> · Pre-meeting brief</div>
    <div>${modeBadge}</div>
  </header>
  <h1>${esc(brief.meeting.title)}</h1>
  <p class="sub">${brief.prospects.length} prospect ${plural(brief.prospects.length, "company", "companies")}${when} · generated ${esc(brief.generatedAt.slice(0, 16).replace("T", " "))} UTC</p>
  ${sections}
  <footer class="foot">Generated by Granola Meeting-Prep · research via Parallel.ai Task API</footer>
</div>
</body>
</html>`;
}

function renderProspect(p: ProspectResearch): string {
  const c = p.company.value;
  const accent = safeAccent(c.primary_brand_color_hex, GRANOLA_PURPLE);
  const onAccent = readableTextOn(accent);
  const tierClass = p.icp.tier.toLowerCase();

  const facts: Array<[string, string]> = [
    ["Industry", c.industry],
    ["HQ", c.hq_location],
    ["Headcount", `${c.employee_count} (${c.headcount_trend})`],
    ["Funding", c.total_funding],
    ["Recent signals", c.recent_signals],
    ["Open GTM roles", c.open_gtm_roles],
    ["Meeting culture", c.meeting_culture_signal],
  ];

  return `
  <section class="card">
    <div class="card-head" style="background:${accent};color:${onAccent}">
      <img class="logo" src="${esc(logoUrl(p.domain))}" alt="${esc(c.legal_name)} logo"
           onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'logo mono',textContent:'${esc(monogram(c.legal_name))}'}))" />
      <div class="card-head-text">
        <h2>${esc(c.legal_name)}</h2>
        <p>${esc(c.one_liner)}</p>
        <a href="${esc(c.website)}" style="color:${onAccent}">${esc(p.domain)}</a>
      </div>
      <div class="icp icp-${tierClass}">
        <div class="icp-score">${p.icp.score}</div>
        <div class="icp-tier">${esc(p.icp.tier)} fit</div>
      </div>
    </div>

    <div class="card-body">
      <table class="facts">
        ${facts.map(([k, v]) => `<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join("")}
      </table>

      <details class="icp-why" open>
        <summary>Why this ICP score</summary>
        <ul>${p.icp.reasons.map((r) => `<li>${esc(r)}</li>`).join("")}</ul>
      </details>

      <h3 class="people-h">Attendees (${p.people.length})</h3>
      ${p.people.map((person) => renderPerson(person, accent)).join("")}

      ${renderCitations(collectCitations(p))}
    </div>
  </section>`;
}

function renderPerson(
  person: ProspectResearch["people"][number],
  accent: string,
): string {
  const v = person.value;
  return `
      <div class="person" style="border-left-color:${accent}">
        <div class="person-top">
          <strong>${esc(v.full_name)}</strong>
          <span class="muted">${esc(v.current_title)} · ${esc(v.seniority)} · ${esc(v.role_function)}</span>
          ${v.linkedin_url ? `<a href="${esc(v.linkedin_url)}">LinkedIn ↗</a>` : ""}
        </div>
        <p class="meeting-int">🗓 Meeting intensity: ${esc(v.meeting_intensity)}</p>
        <p>${esc(v.background)}</p>
        ${v.recent_activity && v.recent_activity !== "None found" ? `<p class="recent">📡 ${esc(v.recent_activity)}</p>` : ""}
        <div class="talk">
          <span class="talk-h">Talking points</span>
          <p>${esc(v.talking_points)}</p>
        </div>
      </div>`;
}

function renderCitations(citations: Citation[]): string {
  if (citations.length === 0) return "";
  const items = citations
    .map((c) => `<li><a href="${esc(c.url)}">${esc(c.title ?? c.url)}</a></li>`)
    .join("");
  return `<details class="sources"><summary>Sources (${citations.length})</summary><ol>${items}</ol></details>`;
}

function collectCitations(p: ProspectResearch): Citation[] {
  const all: Citation[] = [];
  const push = (r: Researched<unknown>) => {
    for (const e of Object.values(r.evidence)) all.push(...e.citations);
  };
  push(p.company);
  p.people.forEach(push);
  // De-dupe by URL.
  const seen = new Set<string>();
  return all.filter((c) => (seen.has(c.url) ? false : (seen.add(c.url), true)));
}

function esc(s: string): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function plural(n: number, one: string, many: string): string {
  return n === 1 ? one : many;
}

const STYLES = `
:root { --ink:#1a1a2e; --muted:#6b7280; --line:#e5e7eb; --bg:#f7f7fb; }
* { box-sizing:border-box; }
body { margin:0; background:var(--bg); color:var(--ink);
  font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width:860px; margin:0 auto; padding:32px 20px 64px; }
.top { display:flex; justify-content:space-between; align-items:center; margin-bottom:24px; }
.brand { font-weight:600; color:var(--muted); }
.brand span { color:var(--ink); }
h1 { font-size:30px; margin:0 0 4px; letter-spacing:-0.02em; }
.sub { color:var(--muted); margin:0 0 28px; }
.chip { font-size:11px; font-weight:700; letter-spacing:0.04em; padding:4px 10px; border-radius:999px; }
.chip-live { background:#dcfce7; color:#166534; }
.chip-mock { background:#fef3c7; color:#92400e; }
.card { background:#fff; border:1px solid var(--line); border-radius:16px; overflow:hidden;
  margin-bottom:28px; box-shadow:0 1px 3px rgba(0,0,0,.05); }
.card-head { display:flex; align-items:center; gap:16px; padding:20px 24px; }
.logo { width:56px; height:56px; border-radius:12px; background:#fff; object-fit:contain; padding:6px; flex:none; }
.logo.mono { display:flex; align-items:center; justify-content:center; font-weight:700; color:#333; font-size:20px; }
.card-head-text { flex:1; min-width:0; }
.card-head-text h2 { margin:0; font-size:21px; }
.card-head-text p { margin:2px 0 4px; opacity:.92; font-size:14px; }
.card-head-text a { font-size:12px; text-decoration:none; opacity:.85; }
.icp { text-align:center; background:rgba(255,255,255,.16); border-radius:12px; padding:8px 14px; flex:none; }
.icp-score { font-size:28px; font-weight:800; line-height:1; }
.icp-tier { font-size:11px; text-transform:uppercase; letter-spacing:.05em; margin-top:2px; }
.card-body { padding:20px 24px 24px; }
.facts { width:100%; border-collapse:collapse; margin-bottom:16px; }
.facts th { text-align:left; width:150px; vertical-align:top; color:var(--muted); font-weight:600;
  padding:6px 12px 6px 0; font-size:13px; }
.facts td { padding:6px 0; border-bottom:1px solid var(--line); }
details { margin:12px 0; }
summary { cursor:pointer; font-weight:600; font-size:14px; color:var(--ink); }
.icp-why ul { margin:8px 0 0; padding-left:18px; color:var(--muted); font-size:13px; }
.icp-why li { margin:3px 0; }
.people-h { font-size:13px; text-transform:uppercase; letter-spacing:.05em; color:var(--muted); margin:20px 0 10px; }
.person { border-left:3px solid; padding:8px 0 8px 14px; margin-bottom:16px; }
.person-top { display:flex; gap:10px; align-items:baseline; flex-wrap:wrap; }
.person-top a { font-size:12px; color:#6C5CE7; text-decoration:none; }
.muted { color:var(--muted); font-size:13px; }
.meeting-int { margin:6px 0; font-size:13px; }
.recent { font-size:13px; color:#374151; }
.talk { background:#f5f3ff; border-radius:10px; padding:10px 14px; margin-top:8px; }
.talk-h { font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; color:#6C5CE7; }
.talk p { margin:4px 0 0; }
.sources ol { margin:8px 0 0; padding-left:20px; font-size:13px; }
.sources a { color:#6C5CE7; }
.foot { color:var(--muted); font-size:12px; text-align:center; margin-top:32px; }
.icp-strong .icp-score { color:#bbf7d0; } .icp-moderate .icp-score { color:#fde68a; } .icp-weak .icp-score { color:#fecaca; }
`;
